version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/mlflow_logs:/mlflow_logs 
    networks:
      - app-network

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    command: mlflow ui --backend-store-uri /mlflow_logs --host 0.0.0.0 --port 5000
    volumes:
      - ./backend/mlflow_logs:/mlflow_logs
    networks:
      - app-network

  frontend-blue:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: react-frontend-blue
    expose:
      - "80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app-network
    depends_on:
      - backend


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-blue
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge
