name: Docker Build

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            path: ./backend
          - name: frontend
            path: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short commit ID
        run: echo "COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.path }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.COMMIT_ID }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:latest